name: Build and test

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check codestyle
        run: git ls-files *.{c,h} | xargs clang-format -i && git diff --exit-code
        
      - name: Build
        run: make
        
      - name: Run tests
        run: make test && ./libchessviz-test